import type { Destination } from "@/lib/india";

export type PlanInput = { destination: Destination; budget: number; days: number; travellers: number };
export type PlaceDetail = {
  name: string; address: string; why: string; seeDo: string; duration: string; bestTime: string;
  hours: string; entryFee: string; fromPrevious: string; transport: string; localCost: number;
  nearbyFood: string; tips: string; booking: string; mapUrl: string;
};
export type DayPlan = {
  day: number; title: string; segment: string; places: string[]; order: string; timing: string;
  transport: string; food: string; stay: string; cost: number; note: string; stops: PlaceDetail[];
  dailyBreakdown: { transport: number; food: number; entry: number; activities: number; accommodation: number; total: number };
};
type CityPlan = { subtitle: string; places: PlaceDetail[]; food: string; stay: string; transport: string; dayTitles: string[]; sourceNote: string };

const map = (name: string) => `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(name)}`;
const place = (name: string, address: string, why: string, seeDo: string, duration: string, bestTime: string, hours: string, entryFee: string, fromPrevious: string, transport: string, localCost: number, nearbyFood: string, tips: string, booking = "No advance booking indicated; verify locally before visiting."): PlaceDetail => ({ name, address, why, seeDo, duration, bestTime, hours, entryFee, fromPrevious, transport, localCost, nearbyFood, tips, booking, mapUrl: map(`${name}, ${address}`) });

const cityPlans: Record<string, CityPlan> = {
  RSH: {
    subtitle: "Ghats, suspension bridges, ashrams and Himalayan river views",
    places: [
      place("Triveni Ghat", "Mayakund, Rishikesh, Uttarakhand 249201", "Rishikesh's best-known bathing ghat and a central place for the evening Ganga Aarti.", "Walk the stepped riverfront, sit beside the Ganga and attend the evening aarti.", "1–1.5 hours", "Early morning or before evening aarti", "Information unavailable; confirm current aarti time locally.", "Free; donations optional", "Starting point", "Walk or auto/e-rickshaw", 80, "Local market and vegetarian eateries around Mayakund", "Reach before the aarti for a clear viewing spot; keep valuables secure."),
      place("Bharat Mandir", "Jhanda Chowk, near Triveni Ghat, Rishikesh", "An old Vishnu shrine close to the central ghat area and a useful heritage stop.", "See the shrine and carved religious details; dress respectfully.", "30–45 minutes", "Morning", "Information unavailable; verify temple hours before visiting.", "Free; donations optional", "5–10 minutes from Triveni Ghat", "Walk or auto/e-rickshaw", 50, "Vegetarian breakfast options near Triveni Ghat", "Follow temple photography and dress rules."),
      place("Ram Jhula", "Swargashram, Rishikesh, Uttarakhand", "A landmark suspension bridge connecting riverside ashram areas and market lanes.", "Cross the bridge on foot and pause for river and foothill views.", "45–60 minutes", "Morning or late afternoon", "Bridge access can change; verify current pedestrian restrictions.", "Free", "25–35 minutes from Bharat Mandir", "Auto to Swargashram, then walk", 120, "Food stalls and vegetarian cafes in Swargashram", "It can be crowded; walk slowly and follow local access signs."),
      place("Parmarth Niketan", "Swargashram, Rishikesh, Uttarakhand 249304", "A riverside ashram known for yoga, meditation and Ganga-facing spiritual activities.", "Walk the riverside campus and check the current public programme or aarti viewing arrangements.", "1–1.5 hours", "Late afternoon or evening", "Programme timings vary; check the ashram directly.", "Information unavailable; programme-specific fees may apply", "10 minutes from Ram Jhula", "Walk or auto/e-rickshaw", 70, "Vegetarian ashram meals and nearby cafes", "Respect quiet areas; confirm whether a programme requires registration."),
      place("Beatles Ashram / Chaurasi Kutia", "Swargashram, near Rajaji National Park, Rishikesh", "The former Maharishi Mahesh Yogi ashram with meditation cells, forest paths and mural-covered ruins.", "Explore the meditation huts, forest paths and Beatles-era artwork.", "1.5–2 hours", "Morning or late afternoon", "Information unavailable; confirm gate hours before visiting.", "Estimated ticket; verify current fee at the official entrance", "15–25 minutes from Parmarth Niketan", "Auto/e-rickshaw to the entrance", 150, "Vegetarian cafes around Swargashram", "Wear comfortable shoes; follow photography and conservation rules."),
      place("Lakshman Jhula", "Tapovan–Jonkm, Rishikesh, Uttarakhand", "An iconic river crossing and one of the most recognisable Rishikesh viewpoints.", "See the river corridor, nearby temples and market lanes; use the currently open crossing or official alternative if access is restricted.", "45–60 minutes", "Early morning or sunset", "Access status can change; verify before setting out.", "Free", "30–45 minutes from Beatles Ashram area", "Auto/e-rickshaw; walk near the bridge", 150, "Tea, snacks and vegetarian cafes in Tapovan", "Do not assume the bridge is open; check local signage on the day."),
      place("Neer Garh Waterfall", "Neer Garh, near Tapovan, Rishikesh, Uttarakhand", "A short nature outing with forest trail sections and waterfall pools outside the central ghats.", "Walk the marked trail and enjoy the cascade; avoid unsafe water levels.", "2–3 hours including trail", "Morning, outside peak heat", "Trail conditions and access vary seasonally; verify locally.", "Estimated local entry fee; verify current fee", "25–40 minutes from Lakshman Jhula area", "Auto to trailhead, then walk", 300, "Carry water; food options are limited near the trail", "Wear shoes with grip; do not enter pools after heavy rain."),
      place("Shatrughan Temple Ghat", "Rishikesh riverfront, Uttarakhand", "A quieter riverside stop for pilgrims and travellers who want a less crowded ghat experience.", "Sit by the river, observe local rituals and walk the adjoining riverfront.", "45–60 minutes", "Morning or sunset", "Information unavailable; confirm access locally.", "Free", "15–25 minutes from central Rishikesh by auto", "Auto/e-rickshaw or walking from nearby riverfront", 100, "Simple vegetarian eateries in central Rishikesh", "Keep the riverfront clean and follow local bathing guidance."),
    ],
    food: "Estimated local meals: vegetarian thali, kachori-sabzi, lassi and cafe food; restaurant names and prices are not confirmed.",
    stay: "Estimated budget stay around Tapovan, Swargashram or central Rishikesh; verify live availability before booking.",
    transport: "Walking for close riverfront clusters + auto/e-rickshaw between central Rishikesh, Swargashram and Tapovan.",
    dayTitles: ["Central ghats and evening aarti", "Swargashram ashrams and Beatles Ashram", "Bridges, waterfall and quieter riverfront"],
    sourceNote: "Named Rishikesh attractions and broad location relationships are based on the Uttarakhand Tourism destination guide. Hours, fees and availability are marked for verification where the source does not publish a current value.",
  },
  DEL: {
    subtitle: "Central Delhi landmarks, Old Delhi lanes and Mughal heritage",
    places: [
      place("India Gate", "Kartavya Path, New Delhi 110001", "A prominent war memorial and open public landmark in central Delhi.", "Walk the memorial axis and surrounding lawns; pair with Kartavya Path.", "1–1.5 hours", "Early morning or after sunset", "Open-area access can change for events; verify locally.", "Free", "Starting point", "Delhi Metro + short auto", 100, "Cafes and casual food around central Delhi", "Avoid peak afternoon heat and crowded event periods."),
      place("Humayun's Tomb", "Mathura Road, Nizamuddin East, New Delhi 110013", "A major Mughal garden-tomb and a useful southern-central heritage cluster.", "Walk the charbagh garden and inspect the tomb complex architecture.", "1.5–2 hours", "Morning or late afternoon", "Confirm current ASI hours before visiting.", "Estimated monument ticket; verify current fee", "25–35 minutes from India Gate", "Metro to JLN Stadium/Nizamuddin area + auto", 180, "Nizamuddin area has many food options; verify venue details", "Carry water and allow time for security."),
      place("Qutub Minar", "Mehrauli, New Delhi 110030", "A UNESCO-listed minaret complex with layered Delhi Sultanate architecture.", "Explore the minar, mosque remains and surrounding archaeological structures.", "2 hours", "Morning", "Confirm current ASI hours before visiting.", "Estimated monument ticket; verify current fee", "35–50 minutes from Humayun's Tomb", "Metro toward Qutub Minar + auto", 220, "Mehrauli and Saket have varied food options", "Wear comfortable shoes; the complex involves walking."),
      place("Red Fort", "Netaji Subhash Marg, Lal Qila, Old Delhi 110006", "A major Mughal fort and one of Old Delhi's defining heritage sites.", "Walk the fort courtyards and palace structures; check current museum access.", "2–3 hours", "Morning", "Confirm current ASI hours and closure day.", "Estimated monument ticket; verify current fee", "40–55 minutes from Qutub Minar", "Metro to Lal Qila/Chandni Chowk + walk", 200, "Old Delhi food options; use hygienic, currently open vendors", "Expect security checks and crowds."),
      place("Chandni Chowk", "Old Delhi, Delhi 110006", "A dense historic market district with food, shops and religious landmarks.", "Walk selected lanes and sample local snacks from currently operating vendors.", "2–3 hours", "Late afternoon", "Market hours vary by lane and day; verify locally.", "Free; food is pay-as-you-go", "10–15 minutes from Red Fort", "Walk or cycle-rickshaw", 250, "Chaat, paratha and sweets; choose busy, hygienic outlets", "Keep belongings close in crowded lanes."),
    ],
    food: "Estimated local meals: Delhi thali, chaat and a sit-down dinner; restaurant availability and prices require live verification.", stay: "Estimated budget stay around Paharganj or Karol Bagh; verify live availability before booking.", transport: "Delhi Metro + short auto-rickshaw rides.", dayTitles: ["Central Delhi and Nizamuddin", "Mehrauli and Old Delhi heritage", "Markets and flexible Delhi time"], sourceNote: "Place names and addresses are stable landmark references; current ticket fees and hours require live verification.",
  },
  JAI: {
    subtitle: "Amber Fort, Jaipur old city and bazaar lanes",
    places: [
      place("Amber Fort", "Devisinghpura, Amer, Jaipur, Rajasthan 302028", "A hill fort complex with courtyards, palaces and views over the surrounding landscape.", "Explore the fort courtyards and palace interiors; use only authorised guides and ticket counters.", "2.5–3 hours", "Morning", "Confirm current monument hours and ticket rules.", "Estimated monument ticket; verify current fee", "35–50 minutes from central Jaipur", "App cab/auto or city bus", 300, "Food options near Amer; verify current vendors", "Start early to avoid heat and crowds."),
      place("City Palace", "Tulsi Marg, Gangori Bazaar, Jaipur 302002", "A central royal complex that anchors the old-city heritage cluster.", "Visit the courtyards, galleries and museum spaces open on the day.", "1.5–2 hours", "Late morning", "Confirm current opening hours and museum access.", "Estimated ticket; verify current fee", "35–45 minutes from Amber Fort", "Auto/cab", 180, "Old City vegetarian restaurants and cafes", "Dress for walking and sun."),
      place("Jantar Mantar", "Gangori Bazaar, Jaipur 302002", "An observatory with historic astronomical instruments beside City Palace.", "See the large masonry instruments and read the interpretation panels.", "45–60 minutes", "Late morning", "Confirm current hours.", "Estimated ticket; verify current fee", "5 minutes from City Palace", "Walk", 50, "City Palace/old-city food options", "Best paired with City Palace to reduce travel."),
      place("Hawa Mahal", "Hawa Mahal Road, Badi Choupad, Jaipur 302002", "A distinctive pink sandstone facade and one of Jaipur's best-known old-city landmarks.", "View the facade, visit the interior if open and photograph the old-city streets.", "45–75 minutes", "Early morning", "Confirm current hours.", "Estimated ticket; verify current fee", "10–15 minutes from Jantar Mantar", "Walk or short auto", 80, "Old-city kachori, lassi and vegetarian meals", "Roadside viewing is busy; keep to safe pedestrian areas."),
      place("Johari Bazaar", "Johari Bazaar Road, Jaipur 302003", "A historic market area for jewellery, textiles and everyday city life.", "Browse selected lanes and compare prices before buying.", "1.5–2 hours", "Late afternoon", "Market days and opening hours vary; verify locally.", "Free; purchases are pay-as-you-go", "10 minutes from Hawa Mahal", "Walk or auto", 100, "Kachori and sweets from currently open vendors", "Bargain respectfully and keep receipts."),
    ], food: "Estimated local meals: Rajasthani thali, kachori and lassi; venue pricing is not confirmed.", stay: "Estimated budget stay around MI Road or Bani Park; verify live availability.", transport: "Auto-rickshaw/cab between Amer and the walkable Old City cluster.", dayTitles: ["Amer and Jaipur old city", "Royal observatory and markets", "Slow Jaipur morning and bazaar time"], sourceNote: "Landmark names and neighbourhood addresses are stable references; hours and entry fees require current verification.",
  },
  GOI: {
    subtitle: "Panaji heritage, Old Goa churches and the Mandovi coast",
    places: [
      place("Basilica of Bom Jesus", "Old Goa, Goa 403402", "A major Old Goa heritage church and a key stop in the historic church cluster.", "Visit the basilica interior and surrounding heritage precinct respectfully.", "45–75 minutes", "Morning", "Confirm current visiting hours and service restrictions.", "Estimated/subject to current rules", "35–50 minutes from Panaji", "Bus or app cab", 350, "Food options in Panaji; verify open venues", "Avoid service times for sightseeing and dress respectfully."),
      place("Sé Cathedral", "Velha Goa, Goa 403110", "A prominent Old Goa cathedral located close to the Basilica cluster.", "See the church architecture and Old Goa heritage landscape.", "30–45 minutes", "Morning", "Confirm current visiting hours.", "Estimated/subject to current rules", "5–10 minutes from Basilica", "Walk within Old Goa cluster", 40, "Carry water; food options are limited within the monument cluster", "Follow photography and dress rules."),
      place("Fontainhas", "Fontainhas, Panaji, Goa 403001", "A historic Latin Quarter with colourful houses and narrow lanes.", "Walk the lanes and observe the neighbourhood without blocking residents.", "1–1.5 hours", "Late afternoon", "Residential area; access is public but businesses vary.", "Free", "20–30 minutes from Old Goa", "Bus or cab", 120, "Panaji cafes; verify current menus and prices", "Keep noise low and respect private homes."),
      place("Miramar Beach", "Miramar, Panaji, Goa 403001", "A convenient Panaji beach for an open sunset and coastal walk.", "Walk the beach and watch sunset; follow local swimming warnings.", "1–1.5 hours", "Sunset", "Open beach; conditions and access can change.", "Free", "10–15 minutes from Fontainhas", "Auto/cab", 120, "Food options along the Panaji coast; verify vendors", "Avoid swimming in unsafe conditions."),
      place("Dona Paula Viewpoint", "Dona Paula, Panaji, Goa 403004", "A coastal viewpoint over the harbour and nearby shoreline.", "Take in the viewpoint and coastal scenery.", "45–60 minutes", "Late afternoon", "Access and vendor hours vary; verify locally.", "Free/estimated depending on access area", "20–30 minutes from Miramar", "Cab or local bus", 180, "Nearby cafes; verify current availability", "Expect traffic around peak sunset."),
    ], food: "Estimated local meals: Goan thali, seafood or vegetarian cafe food; verify current vendors and prices.", stay: "Estimated budget stay near Panaji, Calangute or Palolem depending on route; verify live availability.", transport: "Bus + shared taxi/cab; scooter cost excluded from estimates.", dayTitles: ["Old Goa heritage cluster", "Panaji lanes and sunset coast", "Flexible coastal morning"], sourceNote: "Place names are established Goa heritage/coastal landmarks; current access, fees and hours require verification.",
  },
  BOM: {
    subtitle: "South Mumbai icons, heritage rail architecture and sea views",
    places: [
      place("Gateway of India", "Apollo Bandar, Colaba, Mumbai 400001", "A landmark waterfront arch and starting point for the Colaba heritage area.", "See the monument and harbour frontage; ferry departures require separate verification.", "45–60 minutes", "Early morning or evening", "Open-area access can change for security reasons.", "Free; boat tickets separate and estimated", "Starting point", "Local train to Churchgate/CST + bus/cab", 180, "Colaba eateries; verify current prices", "Expect crowds and security checks."),
      place("Chhatrapati Shivaji Maharaj Terminus", "Chhatrapati Shivaji Terminus Area, Mumbai 400001", "A UNESCO-listed railway terminus with landmark Gothic architecture.", "View the exterior and public-access areas without obstructing passengers.", "45–60 minutes", "Morning or late afternoon", "Station access follows railway/security rules.", "Free for public areas", "25–35 minutes from Gateway of India", "Walk or local train", 80, "Fort/CST food options; verify vendors", "Do not enter restricted railway areas."),
      place("Chhatrapati Shivaji Maharaj Vastu Sangrahalaya", "Mahatma Gandhi Road, Kala Ghoda, Mumbai 400023", "A major museum in the Kala Ghoda cultural district.", "Explore current galleries and exhibitions.", "2 hours", "Late morning", "Confirm current museum hours and closure day.", "Estimated museum ticket; verify current fee", "15–20 minutes from Gateway", "Walk/cab", 150, "Kala Ghoda cafes and restaurants", "Allow extra time for current exhibitions."),
      place("Marine Drive", "Netaji Subhash Chandra Bose Road, Mumbai 400002", "Mumbai's iconic seafront promenade and sunset viewpoint.", "Walk the promenade and watch the changing light over the bay.", "1–1.5 hours", "Sunset or after dark", "Open promenade; weather and safety conditions vary.", "Free", "20–30 minutes from Kala Ghoda", "Local train to Churchgate + walk", 80, "Nearby snack vendors; verify hygiene and prices", "Stay on the promenade and avoid unsafe sea edges."),
      place("Sanjay Gandhi National Park", "Borivali East, Mumbai 400066", "A large protected urban park offering a greener, longer excursion.", "Walk selected visitor trails and check current safari/cave options.", "3–4 hours", "Morning", "Confirm current park hours, entry and activity availability.", "Estimated park/activity ticket; verify current fee", "45–75 minutes from Marine Drive", "Local train to Borivali + auto", 300, "Carry water; food options inside vary", "Plan this as a separate north-Mumbai day due to travel time."),
    ], food: "Estimated local meals: vada pav, thali and neighbourhood restaurants; live venue pricing is unavailable here.", stay: "Estimated budget stay around Dadar, Andheri or Colaba outskirts; verify live availability.", transport: "Local train + metro + short cab rides.", dayTitles: ["Colaba and Fort heritage", "Kala Ghoda and Marine Drive", "Green Mumbai day"], sourceNote: "Landmark names and neighbourhood references are stable; current museum/park fees and hours require verification.",
  },
  VNS: {
    subtitle: "Ghats, old-city lanes, Sarnath and living cultural heritage",
    places: [
      place("Dashashwamedh Ghat", "Godowlia, Varanasi, Uttar Pradesh 221001", "A central ghat associated with the evening Ganga Aarti and riverfront activity.", "Walk the ghat steps and attend the aarti from a respectful public viewing area.", "1.5 hours", "Before evening aarti", "Aarti time varies by season; confirm locally.", "Free; boat viewing separate", "Starting point", "Walk/e-rickshaw; use official boat counters only", 120, "Vegetarian food in Godowlia lanes", "Arrive early and follow crowd/security instructions."),
      place("Assi Ghat", "Assi Ghat Road, Varanasi, Uttar Pradesh 221005", "A broad southern ghat popular for sunrise, riverfront walks and cultural programmes.", "See sunrise, walk the riverfront and check the day's public cultural programme.", "1–1.5 hours", "Sunrise", "Open riverfront; programmes vary.", "Free", "25–35 minutes from Dashashwamedh by auto", "Auto/e-rickshaw or boat", 140, "Kachori, lassi and cafes nearby", "Keep the riverfront clean and respect bathing areas."),
      place("Sarnath", "Sarnath, Varanasi, Uttar Pradesh 221007", "A major Buddhist heritage site a short trip from Varanasi.", "Visit the archaeological area and nearby museum if open.", "3 hours", "Morning", "Confirm current ASI/museum hours and closure day.", "Estimated monument/museum ticket; verify current fee", "35–50 minutes from Assi Ghat", "Auto/cab", 350, "Carry water; food options are outside the heritage area", "Allow time for security and walking."),
      place("Kashi Vishwanath Temple Corridor", "Lahori Tola, Varanasi, Uttar Pradesh 221001", "A major pilgrimage destination in the old city.", "Follow the current darshan/security process and explore the corridor respectfully.", "1.5–2 hours", "Early morning", "Darshan and entry rules change; verify on the official channel.", "Entry rules/fees vary; verify before visiting", "20–30 minutes from Dashashwamedh", "Walk; vehicles restricted in lanes", 100, "Vegetarian food around Godowlia; verify vendors", "Carry only permitted items and expect queues."),
      place("Manikarnika Ghat", "Manikarnika Ghat, Varanasi, Uttar Pradesh 221001", "A significant cremation ghat that helps explain the city's living cultural landscape.", "Observe from a respectful distance; do not photograph ceremonies without permission.", "30–45 minutes", "Daytime", "Active ceremonial site; access and etiquette are sensitive.", "Free", "10–15 minutes from Dashashwamedh on foot/boat", "Walk or authorised boat", 80, "Eat away from the immediate ceremonial area", "Maintain silence and respect families and rituals."),
    ], food: "Estimated local meals: kachori-sabzi, lassi and vegetarian thali; exact restaurant pricing is not confirmed.", stay: "Estimated budget stay near Assi Ghat or Godowlia; verify live availability.", transport: "Walking + e-rickshaw; use official boating counters only.", dayTitles: ["Sunrise ghats and old lanes", "Sarnath and evening riverfront", "Temple corridor and cultural context"], sourceNote: "Ghat and heritage names are stable references; live darshan, museum hours and fees require verification.",
  },
  BLR: {
    subtitle: "Gardens, palace heritage and central Bengaluru neighbourhoods",
    places: [
      place("Lalbagh Botanical Garden", "Lalbagh Road, Bengaluru, Karnataka 560004", "A historic botanical garden with landscaped paths and the glass house.", "Walk the garden paths and see the current seasonal displays.", "2 hours", "Early morning", "Confirm current gate hours and event access.", "Estimated garden ticket; verify current fee", "Starting point", "Metro + walk/auto", 100, "South Indian breakfast nearby", "Start early for cooler weather and quieter paths."),
      place("Cubbon Park", "Kasturba Road, Bengaluru, Karnataka 560001", "A large central green space close to Bengaluru's museum and civic district.", "Walk the avenues and pair with a nearby museum if open.", "1.5 hours", "Morning or late afternoon", "Park access and sections vary; verify locally.", "Free/estimated for special venues", "25–35 minutes from Lalbagh", "Metro/bus/auto", 90, "Cafes and restaurants around central Bengaluru", "Stay on marked paths."),
      place("Bengaluru Palace", "Vasanth Nagar, Bengaluru, Karnataka 560052", "A landmark palace with Tudor-inspired architecture and grounds.", "Tour the visitor-accessible interiors and grounds.", "1.5–2 hours", "Late morning", "Confirm current visitor hours.", "Estimated ticket; verify current fee", "20–30 minutes from Cubbon Park", "Auto/cab", 180, "Restaurants around Vasanth Nagar", "Photography rules may apply."),
      place("Bangalore Fort", "New Tharagupet, Bengaluru, Karnataka 560018", "A surviving historic fort element in the old city area.", "See the gate and remaining fort structures; pair with nearby markets.", "45–60 minutes", "Morning", "Confirm current access.", "Estimated/subject to current rules", "20–30 minutes from Bengaluru Palace", "Auto/bus", 80, "Local South Indian eateries", "Keep the stop short and combine with the old city."),
      place("Church Street", "Church Street, Bengaluru, Karnataka 560001", "A walkable central street for bookshops, cafes and evening city life.", "Browse the street and choose currently open cafes or shops.", "1.5–2 hours", "Evening", "Business hours vary by venue.", "Free; purchases are pay-as-you-go", "15–25 minutes from Bangalore Fort", "Metro + walk", 100, "Cafes and restaurants; verify live menus", "Check venue closing times before relying on a specific stop."),
    ], food: "Estimated local meals: dosa, South Indian meals and cafe food; live menus and prices require verification.", stay: "Estimated budget stay around Majestic, Indiranagar or Koramangala; verify live availability.", transport: "Metro + BMTC bus + short auto-rickshaw rides.", dayTitles: ["Gardens and central Bengaluru", "Palace and old city", "Neighbourhood culture and food"], sourceNote: "Place names are established Bengaluru landmarks; current opening hours and fees require verification.",
  },
  COK: {
    subtitle: "Fort Kochi heritage lanes, Mattancherry and waterfronts",
    places: [
      place("Chinese Fishing Nets", "Fort Kochi Beach, Kochi, Kerala 682001", "A recognisable waterfront feature and working fishing landscape in Fort Kochi.", "Watch the nets and walk the waterfront respectfully.", "45–60 minutes", "Late afternoon", "Working activity varies by tide and season.", "Free; tip/transaction only if participating", "Starting point", "Walk or auto", 90, "Seafood and Kerala food around Fort Kochi", "Do not obstruct workers or equipment."),
      place("St. Francis Church", "Fort Kochi, Kochi, Kerala 682001", "A historic church in the Fort Kochi heritage cluster.", "View the church architecture and surrounding heritage streets.", "30–45 minutes", "Morning", "Confirm current service/visitor hours.", "Estimated/subject to current rules", "10 minutes from Chinese Fishing Nets", "Walk", 50, "Fort Kochi cafes and restaurants", "Dress respectfully."),
      place("Mattancherry Palace", "Mattancherry, Kochi, Kerala 682002", "A historic palace museum with Kerala mural and royal-history exhibits.", "Visit the museum spaces and murals if open.", "1–1.5 hours", "Morning", "Confirm current museum hours and closure day.", "Estimated museum ticket; verify current fee", "15–25 minutes from Fort Kochi", "Ferry/bus/auto", 140, "Mattancherry vegetarian and coastal food", "Allow for ferry queues."),
      place("Jew Town", "Mattancherry, Kochi, Kerala 682002", "A historic lane network around the Paradesi Synagogue area with antique and spice shops.", "Walk the lanes and browse currently open shops.", "1–1.5 hours", "Late afternoon", "Shop and synagogue hours vary; verify locally.", "Free; venue tickets/purchases separate", "5–10 minutes from Mattancherry Palace", "Walk", 80, "Mattancherry cafes and Kerala meals", "Respect residents and religious sites."),
      place("Marine Drive Kochi", "Marine Drive, Ernakulam, Kochi, Kerala 682011", "A central waterfront promenade for a city-facing evening walk.", "Walk the promenade and view the harbour backwaters.", "1–1.5 hours", "Sunset", "Open promenade; conditions vary.", "Free", "25–40 minutes from Mattancherry", "Ferry/metro/auto", 150, "Ernakulam food options; verify current venues", "Expect weekend crowds."),
    ], food: "Estimated local meals: Kerala meals, appam and a coastal dinner; venue names and prices require verification.", stay: "Estimated budget stay in Fort Kochi or Ernakulam; verify live availability.", transport: "Ferry + metro/bus + auto-rickshaw.", dayTitles: ["Fort Kochi waterfront and heritage", "Mattancherry palace and Jew Town", "Waterfront evening"], sourceNote: "Place names are established Kochi heritage and waterfront landmarks; current hours and fees require verification.",
  },
};

function fallbackPlan(destination: Destination): CityPlan {
  return { subtitle: `${destination.name} planning data needs live verification`, places: [], food: "Information unavailable until live local data is connected.", stay: "Information unavailable until live accommodation data is connected.", transport: "Information unavailable until live route data is connected.", dayTitles: [], sourceNote: `No verified attraction record is bundled for ${destination.name}. The planner will not invent place names, addresses, hours or prices.`, };
}

export function calculatePlanBudget(input: PlanInput) {
  const distanceFactor = input.destination.hubs?.includes("air") ? 1.15 : 0.9;
  const travel = Math.round(850 * input.travellers * distanceFactor);
  const accommodation = Math.round(1100 * Math.max(1, input.days - 1) * Math.max(1, Math.ceil(input.travellers / 2)));
  const food = Math.round(550 * input.days * input.travellers);
  const local = Math.round(180 * input.days * input.travellers);
  const activities = Math.round(250 * input.days * input.travellers);
  const emergency = Math.round((travel + accommodation + food + local + activities) * 0.1);
  const estimatedTotal = travel + accommodation + food + local + activities + emergency;
  const total = Math.min(estimatedTotal, Math.max(0, input.budget));
  return { travel, accommodation, food, local, activities, emergency, estimatedTotal, total, remaining: Math.max(0, input.budget - total), isTight: estimatedTotal > input.budget };
}

export function generateItinerary(input: PlanInput): DayPlan[] {
  const source = cityPlans[input.destination.code] ?? fallbackPlan(input.destination);
  if (source.places.length === 0) return [];
  const budget = calculatePlanBudget(input);
  return Array.from({ length: input.days }, (_, index) => {
    const start = Math.floor(index * source.places.length / input.days);
    const end = Math.max(start + 1, Math.floor((index + 1) * source.places.length / input.days));
    const stops = source.places.slice(start, end).slice(0, 5);
    const dailyTransport = Math.round(budget.local / input.days);
    const dailyFood = Math.round(budget.food / input.days);
    const dailyEntry = Math.round(budget.activities / input.days);
    const dailyActivity = 0;
    const dailyAccommodation = Math.round(budget.accommodation / input.days);
    const dailyTotal = dailyTransport + dailyFood + dailyEntry + dailyActivity + dailyAccommodation;
    return { day: index + 1, title: source.dayTitles[index] ?? `${source.subtitle} · Day ${index + 1}`, segment: index === 0 ? "Morning → Afternoon → Evening" : index % 2 === 0 ? "Morning → Afternoon → Sunset" : "Morning → Afternoon → Night", places: stops.map((item) => item.name), order: stops.map((item) => item.name).join(" → "), timing: "09:00–12:00 · 13:00–16:00 · 17:00–19:00", transport: source.transport, food: source.food, stay: source.stay, cost: dailyTotal, note: `${source.sourceNote} All hours, fees, travel times and availability marked estimated or unavailable must be confirmed before travel.`, stops, dailyBreakdown: { transport: dailyTransport, food: dailyFood, entry: dailyEntry, activities: dailyActivity, accommodation: dailyAccommodation, total: dailyTotal } };
  });
}

export function getDestinationPlan(destination: Destination) { return cityPlans[destination.code]; }
